#!/usr/bin/env python3
"""Convert a BDF bitmap font (ASCII 32..126) into a C header for gfx.c.

    python3 tools/mkfont.py spleen-6x12.bdf main/fonts/font_6x12.h font_6x12

Output layout: one row per byte-row, MSB = leftmost pixel, `bpr` bytes per
row, `h` rows per glyph, glyphs stored consecutively from ' ' to '~'.
"""
import sys, re

def parse(path):
    txt = open(path, encoding="utf-8", errors="replace").read()
    fb = re.search(r"^FONTBOUNDINGBOX (\d+) (\d+) (-?\d+) (-?\d+)", txt, re.M)
    fw, fh, fx, fy = map(int, fb.groups())
    glyphs = {}
    for m in re.finditer(r"STARTCHAR[^\n]*\n(.*?)ENDCHAR", txt, re.S):
        body = m.group(1)
        enc = int(re.search(r"^ENCODING (-?\d+)", body, re.M).group(1))
        if not (32 <= enc <= 126):
            continue
        bbx = re.search(r"^BBX (\d+) (\d+) (-?\d+) (-?\d+)", body, re.M)
        bw, bh, bx, by = map(int, bbx.groups())
        rows = body.split("BITMAP\n", 1)[1].split()
        bits = [int(r, 16) for r in rows]
        # Normalise into the font bounding box: top row index = fh - (by - fy) - bh
        top = fh - (by - fy) - bh
        canvas = [0] * fh
        shift_r = len(rows[0]) * 4 - bw if rows else 0
        for i, v in enumerate(bits):
            y = top + i
            if 0 <= y < fh:
                # right-align the glyph row into bw bits, then place at bx-fx
                row = (v >> shift_r) & ((1 << bw) - 1)
                canvas[y] |= row << (fw - bw - (bx - fx))
        glyphs[enc] = canvas
    return fw, fh, glyphs

def main():
    src, dst, name = sys.argv[1:4]
    fw, fh, glyphs = parse(src)
    bpr = (fw + 7) // 8
    out = []
    out.append("// Generated by tools/mkfont.py from %s - do not edit.\n" % src.split('/')[-1])
    out.append("// Spleen font, Copyright (c) 2018-2026 Frederic Cambus, BSD 2-Clause.\n")
    out.append("#pragma once\n#include <stdint.h>\n\n")
    out.append("static const uint8_t %s_data[] = {\n" % name)
    for enc in range(32, 127):
        rows = glyphs.get(enc, [0] * fh)
        out.append("    /* '%s' */ " % (chr(enc) if enc != 92 else "\\\\"))
        for r in rows:
            for b in range(bpr):
                byte = ((r << (8 * bpr - fw)) >> (8 * (bpr - 1 - b))) & 0xFF
                out.append("0x%02X," % byte)
        out.append("\n")
    out.append("};\n\n")
    out.append("const gfx_font_t %s = { %d, %d, %d, %s_data };\n" % (name, fw, fh, bpr, name))
    open(dst, "w").write("".join(out))
    print("wrote", dst, "%dx%d" % (fw, fh), len(glyphs), "glyphs")

if __name__ == "__main__":
    main()
